### ISSUE TITLE
Add concurrency to the script and optimization.

### ISSUE THREAD

**Issue by Abdulla-Alkhulaqui** [ELTE-Clean/Clean-Administration-Platform#10]
Script should receive as an argument the number of threads it may use to correct the tests.
Check if there is a possibility of making the script naturally more efficient.

**Comment by Mohido** [comment]
Brother @Abdulla-Alkhulaqui, Have you solved this issue yet?

**Comment by Abdulla-Alkhulaqui** [comment]
> Brother @Abdulla-Alkhulaqui, Have you solved this issue yet?

@Mohido 
There you go:
https://github.com/ELTE-Clean/Clean-Administration-Platform/pull/46
