### ISSUE TITLE
Get Submissions Endpoint

### ISSUE THREAD

**Issue by Mohido** [ELTE-Clean/Clean-Administration-Platform#78]
Create an endpoint to retrieve student/s submission/s for a specific task. 

Endpoint URL:
[GET]
`tasks/<taskID>/submissions`
query: 
```
userID=<integer>
solutions=<boolean>
```

If a user ID is specified in the query, then return the submission of that specific user. If not, return all the submissions of the users assigned with that task. `solutions` parameter decides if the solution is required to be returned or not. The default behavior is `false`. Thus, only the grade and the user information are returned.

**Comment by the4t4** [comment]
I think you meant

Endpoint URL:
[GET]
`grades/<taskID>/submissions`

**Comment by Mohido** [comment]
I prefer it to be in the `tasks` api repository. Since after the `/` we have `<taskID>` which is related to the task. 

@the4t4
